foo = {'BLAS': '/mnt/opt/tools/slc6/blas/3.5.0-x86_64-gcc46/lib',
       'PBS_NODENUM': '0',
       'ENVIRONMENT': 'BATCH', 'PBS_O_LANG': 'en_US.UTF-8',
       'GCC_HOME': '/mnt/opt/tools/slc6/gcc/4.6.3',
       'VIRTUALENVWRAPPER_SCRIPT': '-/bin/bash',
       'VIRTUAL_ENV': '/mnt/lustre/home/jbzdak/virtualenvs/torque-submit',
       'SHELL': '/bin/bash', 'HISTSIZE': '10000',
       'MANPATH': ':/mnt/opt/modules/3.3.a.7d05f32/share/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/share/man:/usr/man:/usr/mpi/gcc/openmpi-1.4.3/share/man:/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1/share/man:/mnt/opt/tools/slc6/gcc/4.6.3/share/man:/mnt/opt/tools/slc6/binutils/2.22/share/man',
       'XMODIFIERS': '@im=none',
       'JAVA_HOME': '/mnt/home/jbzdak/tools/java/jdk1.8.0_05',
       'PBS_MICFILE': '/var/spool/torque/aux//116364.qsrv2.cis.gov.plmic',
       'PBS_O_PATH': '/mnt/home/jbzdak/bin:/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1/bin:/mnt/opt/tools/slc6/gcc/4.6.3/bin:/mnt/opt/tools/slc6/binutils/2.22/bin:/usr/lib64/qt-3.3/bin:/mnt/opt/modules/3.3.a.7d05f32/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/mnt/opt/tools/slc6/python-virtualenv/1.11-x86_64-gcc46-python27/bin:/mnt/home/jbzdak/bin:/mnt/lustre/home/jbzdak/virtualenvs/torque-submit/bin',
       'WORKON_HOME': '/mnt/lustre/home/jbzdak//virtualenvs',
       'PYTHONPATH': '::/mnt/home/jbzdak/programs/torque-submitter:/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1/lib/python2.7:/mnt/opt/tools/slc6/python-virtualenv/1.11-x86_64-gcc46-python27/lib/python2.7/site-packages::',
       'PBS_NODEFILE': '/var/spool/torque/aux//116364.qsrv2.cis.gov.pl',
       'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-xXjxCbePsj,guid=308f2e1963cb4c58a744ee8f0030ebf0',
       'ORBIT_SOCKETDIR': '/tmp/orbit-jbzdak',
       'VIRTUALENVWRAPPER_HOOK_DIR': '/mnt/home/jbzdak/.virtualenvs',
       'DESKTOP_SESSION': 'gnome', 'CIS_cis_auto_remove': ':',
       'PBS_QUEUE': 'a12h', 'PYCHARM_HOSTED': '1',
       'PBS_JOBID': '116364.qsrv2.cis.gov.pl', 'MAIL': '/var/spool/mail/jbzdak',
       'SSH_ASKPASS': '/usr/libexec/openssh/gnome-ssh-askpass',
       'HOSTNAME': 'wn1001.cis.gov.pl',
       'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated',
       'module': '() {  eval `/mnt/opt/modules/$MODULE_VERSION/bin/modulecmd bash $*`\n}',
       'LESSOPEN': '|/usr/bin/lesspipe.sh %s', 'PBS_O_LOGNAME': 'jbzdak',
       'PBS_MOMPORT': '15003', 'USER': 'jbzdak', 'HOME': '/mnt/home/jbzdak',
       'PYTHONUNBUFFERED': '1',
       'PS1': '(torque-submit)\\u@\\h \\w $(parse_git_branch)',
       'CIS_COMMON_SCRIPT': '/mnt/opt/modules/3.3.a.7d05f32/.config/common.tcl',
       'XAUTHORITY': '/var/run/gdm/auth-for-jbzdak-Ieu9hq/database',
       'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/6111,unix/unix:/tmp/.ICE-unix/6111',
       'SHLVL': '6',
       '__PY_T_SUBMIT_CALL': 'gAJjZGlsbC5kaWxsCl9jcmVhdGVfZnR5cGUKcQAoY2RpbGwuZGlsbApfbG9hZF90eXBlCnEBVQtQYXJ0aWFsVHlwZXEChXEDUnEEY19fYnVpbHRpbl9fCnByaW50CnEFVQxIZWxsbyBXb3JsZCFxBoVxB050cQhScQku',
       'DISPLAY': '127.0.0.1:23.0', 'WINDOWID': '29360132', 'EDITOR': 'nano',
       'PBS_VNODENUM': '0', 'GDM_KEYBOARD_LAYOUT': 'us',
       'PBS_JOBCOOKIE': '0F6BB80D9A4237C459DF9D950A95A394',
       'PBS_O_HOST': 'interactive0001.cis.gov.pl',
       'PYTHON_HOME': '/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1',
       'CLASSPATH': '/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/bootstrap.jar:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/extensions.jar:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/util.jar:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/jdom.jar:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/log4j.jar:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/trove4j.jar:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin/../lib/jna.jar',
       'GDMSESSION': 'gnome',
       'LAPACK_HOME': '/mnt/opt/tools/slc6/lapack/3.5.0-x86_64-gcc46',
       'PKG_CONFIG_PATH': '::::::/mnt/opt/tools/slc6/lapack/3.5.0-x86_64-gcc46/lib/pkgconfig:/mnt/opt/tools/slc6/blas/3.5.0-x86_64-gcc46/lib/pkgconfig:/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1/lib/pkgconfig',
       'PBS_O_MAIL': '/var/spool/mail/jbzdak',
       'TMPDIR': '/scratch/116364.qsrv2.cis.gov.pl',
       'MODULEPATH': '/mnt/opt/modules/versions:/mnt/opt/modules/$MODULE_VERSION/module_utils:/mnt/opt/modules/$MODULE_VERSION/tools:/mnt/opt/modules/$MODULE_VERSION/apps:/mnt/home/jbzdak/privatemodules::',
       'PBS_NUM_PPN': '1', 'PBS_O_SHELL': '/bin/bash',
       'CIS_python_2_7_5_x86_64_gcc46': '::gcc/4.6.3',
       'LAPACK': '/mnt/opt/tools/slc6/lapack/3.5.0-x86_64-gcc46/lib',
       'BLAS_HOME': '/mnt/opt/tools/slc6/blas/3.5.0-x86_64-gcc46',
       'GTK_RC_FILES': '/etc/gtk/gtkrc:/mnt/home/jbzdak/.gtkrc-1.2-gnome2',
       'CIS_blas_3_5_0_x86_64_gcc46': ':',
       '_LMFILES_': '/mnt/opt/modules/3.3.a.7d05f32/module_utils/cis-env:/mnt/opt/modules/3.3.a.7d05f32/module_utils/cis-auto-remove:/mnt/opt/modules/3.3.a.7d05f32/module_utils/use.own:/mnt/opt/modules/3.3.a.7d05f32/tools/binutils/2.22:/mnt/opt/modules/3.3.a.7d05f32/tools/gcc/4.6.3:/mnt/opt/modules/3.3.a.7d05f32/tools/python/2.7.5-x86_64-gcc46:/mnt/opt/modules/3.3.a.7d05f32/tools/blas/3.5.0-x86_64-gcc46:/mnt/opt/modules/3.3.a.7d05f32/tools/lapack/3.5.0-x86_64-gcc46:/mnt/opt/modules/3.3.a.7d05f32/tools/python-virtualenv/1.11-x86_64-gcc46-python27::::::::::::::',
       'MODULE_VERSION': '3.3.a.7d05f32', 'QTDIR': '/usr/lib64/qt-3.3',
       'LD_LIBRARY_PATH': '::::::/usr/mpi/gcc/openmpi-1.4.3/lib64:/mnt/home/jbzdak/tools/ides/pycharm-community-3.4.1/bin:/mnt/opt/tools/slc6/lapack/3.5.0-x86_64-gcc46/lib:/mnt/opt/tools/slc6/blas/3.5.0-x86_64-gcc46/lib:/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1/lib:/mnt/opt/tools/slc6/gcc/4.6.3/lib64:/mnt/opt/tools/slc6/gcc/4.6.3/lib:/mnt/opt/tools/slc6/binutils/2.22/lib64:/mnt/opt/tools/slc6/binutils/2.22/lib',
       'LANG': 'en_US.UTF-8', 'QTLIB': '/usr/lib64/qt-3.3/lib',
       'VIRTUALENVWRAPPER_PYTHON': 'python2.7',
       'QTINC': '/usr/lib64/qt-3.3/include', 'CIS_AUTO_REMOVE': '1',
       'NCPUS': '1', 'PBS_WALLTIME': '43200', 'G_BROKEN_FILENAMES': '1',
       'CIS_OS_VERSION': 'SLC6',
       'PBS_O_WORKDIR': '/mnt/home/jbzdak/programs/torque-submitter/torque_test',
       '_': '/mnt/lustre/home/jbzdak/virtualenvs/torque-submit/bin/python',
       'PBS_TASKNUM': '1', 'PBS_NUM_NODES': '1', 'USERNAME': 'jbzdak',
       'IMSETTINGS_MODULE': 'none', 'CIS_lapack_3_5_0_x86_64_gcc46': ':',
       'PBS_JOBNAME': 'torque_wrapper.py',
       'LUSTRE_HOME': '/mnt/lustre/home/jbzdak/',
       'NLSPATH': '/usr/dt/lib/nls/msg/%L/%N.cat', 'GNOME_KEYRING_PID': '6101',
       'PBS_GPUFILE': '/var/spool/torque/aux//116364.qsrv2.cis.gov.plgpu',
       'PBS_NP': '1',
       '__PY_T_SUBMIT_DIRNAME': '/mnt/home/jbzdak/programs/torque-submitter/torqsubmit',
       'CVS_RSH': 'ssh', 'CIS_binutils_2_22': ':', 'PYTHONIOENCODING': 'UTF-8',
       'PBS_O_HOME': '/mnt/home/jbzdak', 'QT_IM_MODULE': 'xim',
       'LOGNAME': 'jbzdak',
       'PYTHON_VIRTUALENV_HOME': '/mnt/opt/tools/slc6/python-virtualenv/1.11-x86_64-gcc46-python27',
       'PATH': '/mnt/lustre/home/jbzdak/virtualenvs/torque-submit/bin:/mnt/home/jbzdak/bin::/mnt/opt/modules/3.3.a.7d05f32/bin:/mnt/home/jbzdak/bin::/usr/mpi/gcc/openmpi-1.4.3/bin:/mnt/opt/modules/3.3.a.7d05f32/bin:/mnt/home/jbzdak/bin:/mnt/opt/tools/slc6/python/2.7.5-x86_64-gcc46.cis1/bin:/mnt/opt/tools/slc6/gcc/4.6.3/bin:/mnt/opt/tools/slc6/binutils/2.22/bin:/usr/lib64/qt-3.3/bin:/mnt/opt/modules/3.3.a.7d05f32/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/mnt/opt/tools/slc6/python-virtualenv/1.11-x86_64-gcc46-python27/bin:/mnt/home/jbzdak/bin:/mnt/lustre/home/jbzdak/virtualenvs/torque-submit/bin::/mnt/home/jbzdak/bin:',
       'MSG': 'Hello World!',
       'BINUTILS_HOME': '/mnt/opt/tools/slc6/binutils/2.22',
       'HISTCONTROL': 'ignoredups', 'TERM': 'xterm',
       'PBS_ENVIRONMENT': 'PBS_BATCH',
       'XDG_SESSION_COOKIE': '15d49b859897613f098468dd00000248-1404988138.189655-275875905',
       'PBS_VERSION': 'TORQUE-4.2.7', 'IMSETTINGS_INTEGRATE_DESKTOP': 'yes',
       'HISTFILESIZE': '-1', 'MODULE_VERSION_STACK': '3.3.a.7d05f32',
       'COLORTERM': 'gnome-terminal',
       'SSH_AUTH_SOCK': '/tmp/keyring-IakWti/socket.ssh',
       '__PY_T_SUBMIT_ENV': 'CnNvdXJjZSAke0hPTUV9Ly5iYXNocmMKd29ya29uIHRvcnF1ZS1zdWJtaXQKZXhwb3J0IE1TRz0iSGVsbG8gV29ybGQhIgo=',
       'CIS_gcc_4_6_3': '::binutils/2.22',
       'KRB5CCNAME': 'FILE:/tmp/krb5cc_1656_bHHiS2',
       'PBS_O_SERVER': 'qsrv2.cis.gov.pl',
       'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project',
       'GNOME_KEYRING_SOCKET': '/tmp/keyring-IakWti/socket',
       'CIS_python_virtualenv_1_11_x86_64_gcc46_python27': ':',
       'LOADEDMODULES': 'cis-env:cis-auto-remove:use.own:binutils/2.22:gcc/4.6.3:python/2.7.5-x86_64-gcc46:blas/3.5.0-x86_64-gcc46:lapack/3.5.0-x86_64-gcc46:python-virtualenv/1.11-x86_64-gcc46-python27::::::::::::::',
       'GDM_LANG': 'en_US.UTF-8', 'PBS_O_QUEUE': 'a12h',
       'PWD': '/mnt/home/jbzdak',
       'PIP_DOWNLOAD_CACHE': '/mnt/lustre/home/jbzdak/.pipcache',
       'VIRTUALENVWRAPPER_VIRTUALENV': 'virtualenv-2.7',
       'XFILESEARCHPATH': '/usr/dt/app-defaults/%L/Dt'}